import { InsertLink } from "@mui/icons-material";
import {
  CardContent,
  CardMedia,
  Container,
  ImageList,
  ImageListItem,
  ImageListItemBar,
  Paper,
  Typography,
} from "@mui/material";
import { Stack } from "@mui/system";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import React, { useContext } from "react";
import { ThemeContext } from "../../context/context";
import { projects } from "../../Utils/Data";
import Carousel from "react-material-ui-carousel";

const ProjectIndex = () => {
  const router = useRouter();
  const p = projects.find((p) => p.slug === router.query.project) || [];
  const theme = useContext(ThemeContext);
  const darkMode = theme.state.darkMode;
  return (
    <>
      <Head>
        <title>Project by Rakib Miah</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container
        maxWidth="xl"
        disableGutters
        sx={{
          backgroundColor: darkMode ? "#222" : "white",
          color: darkMode && "white",
          p: 5,
          display: "flex",
          flexDirection: "column",
          gap: 2,
        }}
      >
        <Typography variant="h2">{p?.title}</Typography>
        <Typography variant="body2">{p?.desc}</Typography>
        <Typography variant="h4">Stack</Typography>
        <Stack direction="row" alignItems="center" gap={1}>
          {p?.stack?.split(",")?.map((s) => (
            <Typography
              variant="subtitle2"
              key={s}
              sx={{
                padding: 0.5,
                borderRadius: "10px",
                backgroundColor:
                  s === "React"
                    ? "#439A97"
                    : s === "NextJS"
                    ? "#62B6B7"
                    : s === "Firebase"
                    ? "#678983"
                    : s === "ExpressJS"
                    ? "#CBEDD5"
                    : s === "NodeJS"
                    ? "#FFCAC8"
                    : s === "MUI"
                    ? "#10A19D"
                    : s === "Redux Toolkit"
                    ? "#6D67E4"
                    : s === "Axios"
                    ? "#678983"
                    : s === "MongoDB"
                    ? "#FFB26B"
                    : "#344D67",
              }}
            >
              {s}
            </Typography>
          ))}
        </Stack>
        <Typography variant="h4">Deployments</Typography>
        <Link
          style={{
            display: "flex",
            alignItems: "center",
          }}
          href={`${p?.demo}`}
        >
          <InsertLink /> Web
        </Link>

        <Typography variant="h4">Source Code</Typography>
        <Link
          style={{
            display: "flex",
            alignItems: "center",
          }}
          href={`${p?.github}`}
        >
          <InsertLink /> Github
        </Link>

        <Typography variant="h4">Screenshots</Typography>
        {p?.screenshot?.length === 0 ? (
          <Typography>No screenshot available yet.</Typography>
        ) : (
          <Carousel fullHeightHover>
            {p?.screenshot?.map((item) => (
              <Paper key={item.id} elevation={2}>
                <CardContent
                  sx={{
                    display: "flex",
                    flexDirection: "row",
                    justifyContent: "space-around",
                    alignItems: "center",
                  }}
                >
                  <Typography gutterBottom variant="h5" component="div">
                    {item.title}
                  </Typography>
                  <Link href={item?.img}>
                    <CardMedia
                      component="img"
                      image={item?.img}
                      alt="Image"
                      sx={{
                        cursor: "pointer",
                        objectFit: "contain",
                        objectPosition: "60% 100%",
                        width: "100%",
                        maxHeight: 400,
                      }}
                    />
                  </Link>
                </CardContent>
              </Paper>
            ))}
          </Carousel>
        )}
      </Container>
    </>
  );
};

export default ProjectIndex;
