import Head from "next/head";

import Footer from "../components/Footer";
import Intro from "../components/Intro";
import About from "../components/About";
import Projects from "../components/Projects";

export default function Home() {
  return (
    <>
      <Head>
        <title>Rakib Miah - Fullstack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Intro />
      <About />
      <Projects />
      <Footer />
    </>
  );
}
