import Head from "next/head";
import Footer from "../components/Footer";
import Intro from "../components/Intro";
import About from "../components/About";
import Projects from "../components/Projects";
import Contact from "../components/Contact";
import { useContext } from "react";
import { ThemeContext } from "../context/context";
import Toggle from "../components/Toggle";
import Topbar from "../components/Topbar";
import styles from "../styles/Home.module.css";

export default function Home() {
  const theme = useContext(ThemeContext);
  const darkMode = theme.state.darkMode;
  return (
    <>
      <Head>
        <title>Rakib Miah - Fullstack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          backgroundColor: darkMode ? "#222" : "white",
          color: darkMode && "white",
        }}
        className={styles.app}
      >
        <div className={styles.sections}>
          <div className={styles.section}>
            <Intro />
          </div>
          <div className={styles.section}>
            <Projects />
          </div>
          <div className={styles.section}>
            <Contact />
          </div>
        </div>
      </div>
    </>
  );
}
